name: flutter_navigation_tree
description: "Flutter navigation tree widget"
version: 0.0.1
homepage:

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  custom_lint: ^0.7.5
  very_good_analysis: ^7.0.0

flutter:
